# Generated by Django 4.2.16 on 2024-10-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='created_at',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(),
        ),
    ]
