# Generated by Django 4.2.16 on 2024-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_created_at_tarefa_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='relacionamento',
            field=models.CharField(default='em análise', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
