# Generated by Django 4.2.16 on 2024-10-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_relacionamento_tarefa_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
