# Generated by Django 4.2.16 on 2024-10-21 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0005_usuario_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='horas_trabalhadas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descricao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lista',
            name='tarefas',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.usuario'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='relacionamento',
            field=models.CharField(choices=[('em análise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='em análise', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em Andamento'), ('concluída', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
