# Generated by Django 4.2.16 on 2024-10-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_remove_registro_horas_trabalhadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.usuario'),
        ),
    ]
